url: https://skolacode.github.io

# Site settings
title: SkolaCode
email: ask@skolacode.com
description: "Skolacode, learn code with ease. Kursus Komputer - Computer Courses, #CODE,INVENT,IMPORVE. Belajar CODE dengan mudah."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/skolacode/
  - title: github
    url: https://github.com/skolacode

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
